version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: 2kshop_db_container
        restart: always
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file:
            - .env
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    # Redis Service
    redis:
        image: redis:alpine
        container_name: redis
        env_file:
            - .env
        ports:
            - "6380:6379"
        networks:
            - app-network


    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
            - "8443:443"
        env_file:
            - .env
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app
            - mysql
            - redis

    app:
        build:
            context: .
            dockerfile: DockerfileDev
        image: 2kshop-app
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        environment:
            CONTAINER_ENV: local
        env_file:
            - .env
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - mysql
            - redis

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
